name: Composite actions for release

inputs:
  release_version:
    description: 'The version number to use for the new release, default converts snapshot version in POM to release version'
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: git config
      run: |
        git config user.email "rld@reallifedeveloper.com"
        git config user.name "RealLifeDeveloper"
    - name: Use version number from input
      if: ${{ inputs.release_version != '' }}
      run: |
        mvn versions:set -DnewVersion=${{ inputs.release_version }} -DgenerateBackupPoms=false
        RELEASE_VERSION=${{ inputs.release_version }}
    - name: Use version number from POM
      if: ${{ inputs.release_version == '' }}
      run: |
        mvn versions:set -DremoveSnapshot -DgenerateBackupPoms=false
        RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    - name: Create release branch
      run: |
        git checkout -b release/$RELEASE_VERSION
        git commit -a -m "New release candidate $RELEASE_VERSION"
        git push -u origin release/$RELEASE_VERSION
    - name: Create release tag
      run: |
        git tag v$RELEASE_VERSION
        git push origin v$RELEASE_VERSION
    - name: Bump version number in POM to next snapshot version
      if: ${{ inputs.release_version == '' }}
        git checkout master
        mvn versions:set -DnextSnapshot -DgenerateBackupPoms=false
        git add pom.xml
        git commit -m "Bumped POM to next snapshot version"
        git push