#
# A reusable workflow to build and deploy a Maven documentation site for a project.
#
name: Maven site

permissions:
  contents: read

on:
  workflow_call:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add SSH private key
        run: |
          cat <(echo -e "${{ secrets.MAVEN_SITE_PRIVATE_KEY }}") > ~/.ssh/id_ed25519
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JAVA_VERSION || '21' }}
          distribution: ${{ vars.JAVA_DISTRIBUTION || 'zulu' }}
      - NAME: Configure ~/.m2/settings.xml
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [{
              "id": "reallifedeveloper-site".
              "username": "${env.MAVEN_SITE_USERNAME}"
              "privateKey": "~/.ssh/id_ed25519"
              "passphrase": "${env.MAVEN_SITE_PASSPHRASE}"
            }]
      - name: Add host to ~/.ssh/known_hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          hostname=$(echo ${{ secrets.MAVEN_SITE_URL }} | cut --delimiter '/' --fields 3)
          ssh-keyscan $hostname | grep -v '^#' >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      - name: mvn site
        run: |
          echo "id_ed25519:"
          cat ~/.ssh/id_id25519
          echo "settings.xml:"
          cat ~/.m2/settings.xml
          # mvn -B -Pcoverage,pitest clean install site site:deploy -Dnvd.api.key="${{ secrets.NVD_API_KEY }}" \
          #   -Dreallifedeveloper-site.distributionManagement.url="${{ secrets.MAVEN_SITE_URL }}"
        env:
          MAVEN_SITE_USERNAME: ${{ secrets.MAVEN_SITE_USERNAME }}
          MAVEN_SITE_PASSPHRASE: ${{ secrets.MAVEN_SITE_PASSPHRASE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
