#
# A reusable Github workflow to deploy Maven aritfacts to the Sonatype Maven Central Repository and to GitHub Packages.
#
name: Deploy to Maven Central Repository and GitHub Packages

permissions:
  contents: read

on:
  workflow_call:
    secrets:
      GPG_SECRET_KEY:
        description: 'The GPG key to use to sign the jar files, should use \n for newlines'
        required: true
      GPG_SECRET_KEY_PASSPHRASE:
        description: 'The passphrase for the GPG key'
        required: true
      SONATYPE_CENTRAL_USERNAME:
        description: 'The username used when publishing to central.sonatype.com'
        required: true
      SONATYPE_CENTRAL_PASSWORD:
        description: 'The password (token) used then publishing to central.sonatype.com'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Import GPG secret key
        run: |
          cat <(echo -e "${{ secrets.GPG_SECRET_KEY }}") | gpg --batch --import
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JAVA_VERSION || '21' }}
          distribution: ${{ vars.JAVA_DISTRIBUTION || 'zulu'}}
          server-id: sonatype-central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package to Maven Central
        run: mvn -Prelease,sonatype -B clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JAVA_VERSION || '21' }}
          distribution: ${{ vars.JAVA_DISTRIBUTION || 'zulu'}}
      - name: Publish package to GitHub Packages
        run: mvn -Prelease,github -B clean deploy
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
