#
# A reusable workflow to build and deploy a Maven documentation site for a project.
#
name: Maven site

permissions:
  contents: read

on:
  workflow_call:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JAVA_VERSION || '21' }}
          distribution: ${{ vars.JAVA_DISTRIBUTION || 'zulu' }}
          server-id: reallifedeveloper-site
          server-username: MAVEN_SITE_USERNAME
          server-password: MAVEN_SITE_PASSWORD
      - name: Add github server to ~/.m2/settings.xml
        run: |
          XML='<server>\n<id>github</id>\n<username>${env.GITHUB_ACTOR}</username>\n<password>${env.GITHUB_TOKEN}</password>\n</server>'
          C=$(echo $XML | sed 's/\//\\\//g')
          sed -i "/<\/servers>/ s/.*/${C}\n&/" ~/.m2/settings.xml
          echo
      - name: Add host to ~/.ssh/known_hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          hostname=$(echo ${{ secrets.MAVEN_SITE_URL }} | cut --delimiter '/' --fields 3)
          ssh-keyscan -t rsa $hostname >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      - name: mvn site
        run: |
          mvn -B -P coverage clean integration-test site site:deploy -Dnvd.api.key="${{ secrets.NVD_API_KEY }}" \
            -Dreallifedeveloper-site.distributionManagement.url="${{ secrets.MAVEN_SITE_URL }}"
        env:
          MAVEN_SITE_USERNAME: ${{ secrets.MAVEN_SITE_USERNAME }}
          MAVEN_SITE_PASSWORD: ${{ secrets.MAVEN_SITE_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
