#
# A reusable workflow to run "mvn clean install".
#
name: Maven install

permissions:
  contents: read

on:
  workflow_call:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JAVA_VERSION || '21' }}
          distribution: ${{ vars.JAVA_DISTRIBUTION || 'zulu' }}
      - name: mvn install
        run: mvn -B -DcheckAll clean install