#
# A reusable workflow to create a release branch for a Maven project, update the version numbers and tag the release.
#
name: Create release branch and tag

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      release-version:
        type: string
        description: 'The version number to use for the new release, default converts snapshot version in POM to release version'
        required: false
      main-branch:
        type: string
        description: 'The name of the Git branch containing the code to release, default is main'
        required: false
    secrets:
      GPG_SECRET_KEY:
        description: 'If provided, the GPG key to use to sign the Git release tag, should use \n for newlines'
        required: false
      GPG_SECRET_KEY_PASSPHRASE:
        description: 'If the GPG secret key is provided, this should be the passphrase for the GPG key'
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: reallifedeveloper/github-workflows/.github/actions/maven-release@main
        with:
          release-version: ${{ inputs.release-version }}
          main-branch: ${{ inputs.main-branch }}
          java-version: ${{ vars.JAVA_VERSION || '21' }}
          java-distribution: ${{ vars.JAVA_DISTRIBUTION || 'zulu' }}
          gpg-secret-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-secret-key-passphrase: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
