#
# A reusable workflow to run "mvn clean install".
#
name: Maven install

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      extra-maven-args:
        type: string
        description: 'Extra arguments added to the call to mvn clean install, e.g. "-DcheckAll -Duser.timezone=UTC"'
        required: false
        default: '-DcheckAll'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JAVA_VERSION || '21' }}
          distribution: ${{ vars.JAVA_DISTRIBUTION || 'zulu' }}
      - name: mvn install
        run: mvn -B ${{ inputs.extra-maven-args }} clean install
