name: Create release branch and tag

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      main-branch:
        description: 'The name of the Git branch containing the code to release'
        required: false
        default: 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: ../actions/release
        with:
          main-branch: ${{ inputs.main-branch }}