name: Create release branch and tag

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      release-version:
        type: string
        description: 'The version number to use for the new release, default converts snapshot version in POM to release version'
        required: false
      main-branch:
        type: string
        description: 'The name of the Git branch containing the code to release'
        required: false
        default: 'main'
    secrets:
      GPG_SECRET_KEY:
        description: 'If provided, the GPG key to use to sign the Git release tag, should use \n for newlines'
        required: false
      GPG_SECRET_KEY_PASSPHRASE:
        description: 'If the GPG secret key is provided, this should be the passphrase for the GPG key'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: foo
        run: |
          echo "github.ref=${{ github.ref }}"
          echo "github.head_ref=${{ github.head_ref }}"
          echo "github.workflow_ref=${{ github.workflow_ref }}"
          echo "github.workflow_sha=${{ github.workflow_sha }}"
          # echo "github context: ${{ toJson(github) }}"
          echo "job context: ${{ toJson(job) }}"
          pwd
          ls -laF
          ls -laF ..
          ls -laF ../..
      - uses: ./../github-workflows/.github/actions/release
        with:
          release-version: ${{ inputs.release-version }}
          main-branch: ${{ inputs.main-branch }}
          gpg-secret-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-secret-key-passphrase: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
