name: Update GitHub release

permissions:
  contents: read

on:
  workflow_call:
  workflow_dispatch:

jobs:
  update-github-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: foo
        run: |
          repo_name="${{ github.event.repository.name }}"
          tag="${{ github.ref_name }}"
          echo "repo_name=$repo_name"
          echo "tag=$tag"
