name: Upload signed source tar ball and zip file to a GitHub release

permissions:
  contents: read

on:
  workflow_call:

jobs:
  upload-signed-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: foo
        run: |
          repo_name="${{ github.event.repository.name }}"
          tag="${{ github.ref_name }}"
          echo "repo_name=$repo_name"
          echo "tag=$tag"
          echo "RELEASE_NAME=${repo_name}-${tag/#v/}" >> $GITHUB_ENV
      - name: bar
        run: |
          echo "Creating release ${{ env.RELEASE_NAME }}"
